[package]
name = "webgpu-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
bytemuck = "1.21.0"
cgmath = "0.18.0"
env_logger = "0.11.6"
image = "0.25.5"
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.9"
